package com.tmgl.league.ui.screens.tournaments

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Casino
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.tmgl.league.data.SupabaseConfig
import com.tmgl.league.data.model.Player
import com.tmgl.league.data.model.TournamentRegistration
import com.tmgl.league.ui.format.formatPaddedClock
import com.tmgl.league.ui.theme.TmglGreen
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Columns

private const val REGISTRATION_COLUMNS = "id,tournament_id,player_id"

data class TeeTime(
    val time: String,
    val players: List<String>,
    val hole: Int
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PairingsScreen(
    tournamentId: String,
    roundId: String,
    onBack: () -> Unit
) {
    var registeredPlayers by remember { mutableStateOf<List<Player>>(emptyList()) }
    var pairings by remember { mutableStateOf<List<TeeTime>>(emptyList()) }
    var isLoading by remember { mutableStateOf(true) }
    var error by remember { mutableStateOf<String?>(null) }
    var startTime by remember { mutableStateOf("08:00") }
    var intervalMinutes by remember { mutableStateOf("10") }
    var playersPerGroup by remember { mutableStateOf("4") }
    var startHole by remember { mutableStateOf("1") }
    var isGenerated by remember { mutableStateOf(false) }

    LaunchedEffect(tournamentId) {
        error = null
        if (tournamentId.isBlank()) {
            error = "No tournament ID provided"
            isLoading = false
            return@LaunchedEffect
        }
        try {
            val regs = SupabaseConfig.client.from("tournament_registrations")
                .select(Columns.raw(REGISTRATION_COLUMNS)) { filter { eq("tournament_id", tournamentId) } }
                .decodeList<TournamentRegistration>()
            val playerIds = regs.map { it.playerId }.filter { it.isNotBlank() }.distinct()
            if (playerIds.isNotEmpty()) {
                registeredPlayers = SupabaseConfig.client.from("players")
                    .select(Columns.raw("id,full_name,handicap_index")) { filter { isIn("id", playerIds) } }
                    .decodeList<Player>()
            }
        } catch (e: Exception) {
            error = e.message ?: "Failed to load the registered players"
        }
        isLoading = false
    }

    fun generatePairings() {
        if (registeredPlayers.isEmpty()) return
        val perGroup = (playersPerGroup.toIntOrNull() ?: 4).coerceAtLeast(1)
        val start = startTime.split(":").mapNotNull { it.toIntOrNull() }
        val interval = (intervalMinutes.toIntOrNull() ?: 10).coerceAtLeast(1)
        val hole = ((startHole.toIntOrNull() ?: 1) - 1).coerceAtLeast(0)
        val startHour = start.getOrElse(0) { 8 }
        val startMin = start.getOrElse(1) { 0 }

        val groups = registeredPlayers.shuffled().chunked(perGroup)
        pairings = groups.mapIndexed { index, group ->
            val totalMin = startHour * 60 + startMin + (index * interval)
            val h = (totalMin / 60) % 24
            val m = totalMin % 60
            TeeTime(
                time = formatPaddedClock(h, m),
                players = group.map { it.fullName },
                hole = (hole + index) % 18 + 1
            )
        }
        isGenerated = true
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Pairings & Tee Times") },
                navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Filled.ArrowBack, "Back") } },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = TmglGreen, titleContentColor = Color.White, navigationIconContentColor = Color.White)
            )
        }
    ) { padding ->
        if (isLoading) {
            Box(Modifier.fillMaxSize().padding(padding), contentAlignment = Alignment.Center) { CircularProgressIndicator(color = TmglGreen) }
        } else {
            LazyColumn(modifier = Modifier.padding(padding), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                if (error != null) {
                    item {
                        Text(
                            error ?: "",
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.error
                        )
                    }
                }
                item {
                    Card(modifier = Modifier.fillMaxWidth()) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text("Registered Players: ${registeredPlayers.size}", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)

                            OutlinedTextField(value = startTime, onValueChange = { startTime = it }, label = { Text("Start Time (HH:MM)") }, modifier = Modifier.fillMaxWidth())
                            OutlinedTextField(value = intervalMinutes, onValueChange = { intervalMinutes = it.filter { c -> c.isDigit() } }, label = { Text("Interval (minutes)") }, modifier = Modifier.fillMaxWidth())
                            OutlinedTextField(value = playersPerGroup, onValueChange = { playersPerGroup = it.filter { c -> c.isDigit() } }, label = { Text("Players per group") }, modifier = Modifier.fillMaxWidth())
                            OutlinedTextField(value = startHole, onValueChange = { startHole = it.filter { c -> c.isDigit() } }, label = { Text("Starting hole") }, modifier = Modifier.fillMaxWidth())

                            Button(
                                onClick = { generatePairings() },
                                enabled = registeredPlayers.isNotEmpty(),
                                modifier = Modifier.fillMaxWidth(),
                                colors = ButtonDefaults.buttonColors(containerColor = TmglGreen)
                            ) {
                                Icon(Icons.Default.Casino, contentDescription = null, modifier = Modifier.size(18.dp))
                                Spacer(modifier = Modifier.width(8.dp))
                                Text("Generate Pairings")
                            }
                        }
                    }
                }

                if (isGenerated) {
                    items(pairings) { teeTime ->
                        Card(modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(12.dp), colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)) {
                            Row(modifier = Modifier.padding(12.dp).fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                                Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.width(80.dp)) {
                                    Text(teeTime.time, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.primary)
                                    Text("Hole ${teeTime.hole}", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                }
                                VerticalDivider(modifier = Modifier.height(60.dp).padding(horizontal = 8.dp))
                                Column(modifier = Modifier.weight(1f)) {
                                    teeTime.players.forEach { player ->
                                        Text(player, style = MaterialTheme.typography.bodyMedium)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
